package com.zakhrafa.engine.styles

import com.zakhrafa.engine.models.ComplexDecoration
import com.zakhrafa.engine.models.SideDecoration

object Decorations {
    val complex = listOf(
        ComplexDecoration("♧😈  ", "  ♕🐊", "ÃＢℂᵈ𝕖𝓕𝔾нⓘｊкĹ𝓜Ň𝐨𝐏𝔮𝓡ŞｔยⓋŴ𝓍¥𝐙"),
        ComplexDecoration("😝🍭  ", "  🐙🍔", "α𝐁𝐜ᵈ乇𝕕𝐠Ｈ𝔦𝓙𝓀Ĺ𝓜ᑎσ𝔭ⓠ𝓻şｔ𝕦Ｖ𝕨𝕩ⓨｚ"),
        ComplexDecoration("★彡 ", " 彡★", "ค𝐛℃đＥᶠ𝐆𝓱𝓘ʲ𝓀ᒪм𝓝𝔬卩ΩＲѕŦ𝐮𝔳𝔀𝐱чƵ"),
        ComplexDecoration("(¯´•._.• ", " •._.•´¯)", "卂ⒷｃⒹ乇𝐅𝔾н丨נＫ𝕃爪ŇσƤⓠⓡsｔยⓋᗯЖʸⓏ")
    )

    val side = listOf(
        SideDecoration("╰☆☆ ", " ☆☆╮", "نجوم ╰☆☆"),
        SideDecoration("·.·★ ", " ★·.·", "نجمات ·.·★"),
        SideDecoration("ıllıllı ", " ıllıllı", "ıllıllı"),
        SideDecoration("♥*♡∞:｡.｡ ", " ｡.｡:∞♡*♥", "قلوب ♥"),
        SideDecoration("°o.O ", " O.o°", "عيون °o.O"),
        SideDecoration("¸,ø¤º°`°º¤ø,¸ ", " ¸,ø¤º°`°º¤ø,¸", "زخرفة ¸ø"),
        SideDecoration("꧁༺ ", " ༻꧂", "إطار ملكي"),
        SideDecoration("༺═──────────────═༻ ", " ༺═──────────────═༻", "إطار طويل"),
        SideDecoration("『 ", " 』", "قوس ياباني"),
        SideDecoration("【 ", " 】", "قوس مربع"),
        SideDecoration("《 ", " 》", "قوس مزدوج"),
        SideDecoration("♛ ", " ♛", "تاج"),
        SideDecoration("♕ ", " ♕", "تاج أبيض"),
        SideDecoration("☬ ", " ☬", "رمز ☬"),
        SideDecoration("༒ ", " ༒", "رمز ༒"),
        SideDecoration("ツ ", " ツ", "وجه ツ"),
        SideDecoration("乂 ", " 乂", "ألعاب 乂"),
        SideDecoration("彡 ", " 彡", "ألعاب 彡"),
        SideDecoration("么 ", " 么", "ألعاب 么"),
        SideDecoration("〆 ", " 〆", "ألعاب 〆"),
        SideDecoration("メ ", " メ", "ألعاب メ"),
        SideDecoration("۝ ", " ۝", "زخرفة ۝"),
        SideDecoration("♬ ", " ♬", "تيك توك ♬"),
        SideDecoration("♪ ", " ♪", "تيك توك ♪"),
        SideDecoration("♫ ", " ♫", "تيك توك ♫"),
        SideDecoration("𓆩 ", " 𓆪", "انستقرام"),
        SideDecoration("⟡ ", " ⟡", "ناعم ⟡"),
        SideDecoration("☾ ", " ☽", "قمر"),
        SideDecoration("♡ ", " ♡", "قلب أبيض"),
        SideDecoration("ღ ", " ღ", "قلب ღ"),
        SideDecoration("❥ ", " ❥", "قلب ❥"),
        SideDecoration("❣ ", " ❣", "قلب ❣"),
        SideDecoration("✦ ", " ✦", "نجمة ✦"),
        SideDecoration("✧ ", " ✧", "نجمة ✧"),
        SideDecoration("★ ", " ★", "نجمة ★"),
        SideDecoration("☆ ", " ☆", "نجمة ☆"),
        SideDecoration("✪ ", " ✪", "نجمة ✪"),
        SideDecoration("✫ ", " ✫", "نجمة ✫"),
        SideDecoration("✯ ", " ✯", "نجمة ✯"),
        SideDecoration("✰ ", " ✰", "نجمة ✰"),
        SideDecoration("✿ ", " ✿", "زهرة ✿"),
        SideDecoration("❀ ", " ❀", "زهرة ❀"),
        SideDecoration("❁ ", " ❁", "زهرة ❁"),
        SideDecoration("❃ ", " ❃", "زهرة ❃"),
        SideDecoration("❉ ", " ❉", "زهرة ❉"),
        SideDecoration("✾ ", " ✾", "زهرة ✾"),
        SideDecoration("☘ ", " ☘", "ورقة"),
        SideDecoration("☁ ", " ☁", "سحاب"),
        SideDecoration("⚡ ", " ⚡", "برق"),
        SideDecoration("🔥 ", " 🔥", "نار"),
        SideDecoration("💎 ", " 💎", "ألماس"),
        SideDecoration("✓ ", " ✓", "صح"),
        SideDecoration("✔ ", " ✔", "صح عريض"),
        SideDecoration("☜ ", " ☞", "أسهم يد"),
        SideDecoration("↞ ", " ↠", "أسهم"),
        SideDecoration("⇜ ", " ⇝", "أسهم طويلة"),
        SideDecoration("➳ ", " ➳", "سهم مزخرف"),
        SideDecoration("➶ ", " ➴", "أسهم ناعمة"),
        SideDecoration("☊ ", " ☋", "رموز فلكية"),
        SideDecoration("♚ ", " ♚", "شطرنج"),
        SideDecoration("♜ ", " ♜", "قلعة"),
        SideDecoration("♞ ", " ♞", "حصان"),
        SideDecoration("♟ ", " ♟", "بيدق"),
        SideDecoration("⊰ ", " ⊱", "ناعم ⊰"),
        SideDecoration("⊱⋅ ", " ⋅⊰", "نقاط"),
        SideDecoration("⎝ ", " ⎠", "قوس طويل"),
        SideDecoration("⸨ ", " ⸩", "قوس زخرفة"),
        SideDecoration("⌯ ", " ⌯", "خطاف"),
        SideDecoration("⸙ ", " ⸙", "زخرفة ⸙"),
        SideDecoration("༈ ", " ༈", "تبتي"),
        SideDecoration("࿇ ", " ࿇", "رمز ࿇"),
        SideDecoration("࿔ ", " ࿔", "رمز ࿔"),
        SideDecoration("۞ ", " ۞", "شمس"),
        SideDecoration("֎ ", " ֎", "رمز ֎"),
        SideDecoration("※ ", " ※", "رمز ※"),
        SideDecoration("⁂ ", " ⁂", "ثلاث نجوم"),
        SideDecoration("⁑ ", " ⁑", "نقط مزخرفة"),
        SideDecoration("§ ", " §", "علامة §"),
        SideDecoration("⫷ ", " ⫸", "زاوية"),
        SideDecoration("⫸ ", " ⫷", "زاوية عكس"),
        SideDecoration("▰ ", " ▰", "مربع"),
        SideDecoration("▱ ", " ▱", "مربع أبيض"),
        SideDecoration("◥ ", " ◤", "زوايا"),
        SideDecoration("◢ ", " ◣", "زوايا سفلية"),
        SideDecoration("◄ ", " ►", "مثلث"),
        SideDecoration("◁ ", " ▷", "مثلث أبيض"),
        SideDecoration("▹ ", " ◃", "مثلث صغير"),
        SideDecoration("▸ ", " ◂", "مثلث عريض"),
        SideDecoration("╭─ ", " ─╮", "زاوية علوية"),
        SideDecoration("╰─ ", " ─╯", "زاوية سفلية"),
        SideDecoration("╚══ ", " ══╝", "إطار مزدوج"),
        SideDecoration("╔══ ", " ══╗", "إطار علوي"),
        SideDecoration("▂▃▄▅▆▇█▓▒░ ", " ░▒▓█▇▆▅▄▃▂", "بلوك"),
        SideDecoration("░▒▓█ ", " █▓▒░", "بلوك قصير"),
        SideDecoration("▁▂▃▄▅ ", " ▅▄▃▂▁", "درج"),
        SideDecoration("•._.••´¯``•.¸¸.•` ", " `•.¸¸.•´´¯`••._.•", "كلاسيك"),
        SideDecoration("¸.•´¯`•.¸¸.ஐ ", " ஐ.¸¸.•´¯`•.¸", "ناعم كلاسيك"),
        SideDecoration("-.¸¸.-´¯`-.,¸¸. ", " .¸¸,.-´¯`-.¸¸.-", "خط كلاسيك"),
        SideDecoration("—(••÷[ ", " ]÷••)—", "براكت"),
        SideDecoration("•]••´º´•» ", " «•´º´••[•", "براكت ناعم"),
        SideDecoration("╣[-_-]╠ ", " ╣[-_-]╠", "جيمر"),
        SideDecoration("꧁༒☬ ", " ☬༒꧂", "ملكي ثقيل"),
        SideDecoration("꧁༺♛ ", " ♛༻꧂", "تاج ملكي"),
        SideDecoration("☠︎ ", " ☠︎", "جمجمة"),
        SideDecoration("☣ ", " ☣", "خطر"),
        SideDecoration("☢ ", " ☢", "نووي"),
        SideDecoration("⚔ ", " ⚔", "سيوف"),
        SideDecoration("🜲 ", " 🜲", "نادر"),
        SideDecoration("𖤐 ", " 𖤐", "نجمة نادرة")
    )
}
