name = "zakhrafa-tech"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "zakhrafa.tech", custom_domain = true },
  { pattern = "www.zakhrafa.tech", custom_domain = true }
]

workers_dev = true

[assets]
directory = "html"
binding = "ASSETS"
